name: Build and push to TdA
on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build BE
        uses: docker/build-push-action@v6.8.0
        with:
          context: ./BE/TdA25-BE
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: tda-backend:latest
          outputs: type=docker,dest=/tmp/tda-suiseisquad-backend.tar

      - name: Build FE
        uses: docker/build-push-action@v6.8.0
        with:
          context: ./FE/tda25-fe
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: tda-frontend:latest
          outputs: type=docker,dest=/tmp/tda-suiseisquad-frontend.tar

      - name: Upload Backend Image to TdA
        uses: Tour-de-App/upload-app@tda-25
        with:
          team_token: ${{ secrets.TEAM_TOKEN }}
          image_name: tda-suiseisquad-backend
          image_path: /tmp/tda-suiseisquad-backend.tar

      - name: Upload Frontend Image to TdA
        uses: Tour-de-App/upload-app@tda-25
        with:
          team_token: ${{ secrets.TEAM_TOKEN }}
          image_name: tda-suiseisquad-frontend
          image_path: /tmp/tda-suiseisquad-frontend.tar
